### PR TITLE
Keygen rel

### PR DESCRIPTION
**Pull request by lawlawlaw**
Ready to test deposit

### CODE REVIEW

**Comment by 86667** [comment]
Just a suggestion to improve organisation here:

Since this is testing code might it be sensible to push this to a  "test" or "develop" branch and update Mercury to pull from there. It is then explicit which version is being used. 

I understand that commented code, print statemenets etc. can be useful to keep around for now while the code is being worked on, once its ready for them to be removed and were happy we can push a more complete version to main. 

Thoughts?

**Comment by 86667** [comment]
I think it would be good if we keep a general rule of code being worked on in develop branch, code being tested in test branch and produciton ready code in main.

**Comment by lawlawlaw** [comment]
> Just a suggestion to improve organisation here:
> 
> Since this is testing code might it be sensible to push this to a "test" or "develop" branch and update Mercury to pull from there. It is then explicit which version is being used.
> 
> I understand that commented code, print statemenets etc. can be useful to keep around for now while the code is being worked on, once its ready for them to be removed and were happy we can push a more complete version to main.
> 
> Thoughts?

Ok - I have changed this pull request to merge into develop. So mercury will obviously have to be changed to use the develop branch to use these updates.

Will remove commented code etc before merging to main.

**Comment by lawlawlaw** [comment]
> I think it would be good if we keep a general rule of code being worked on in develop branch, code being tested in test branch and produciton ready code in main.

Ok - have pushed develop and test branches

**Review by tomt1664 — APPROVED** [review]

**Pull request merged**
